### ISSUE TITLE
When does an update to the latest version of acode come out?

### ISSUE THREAD

**Issue by CaRLos1227** [bajrangCoder/acode-plugin-packageAdder#8]
Do you want to release an update to the latest version of acode?

**Comment by bajrangCoder** [comment]
Is there any problem in this plugin with the latest version of Acode?
If yes , then definitely I will provide update.
Please check and tell me

**Comment by CaRLos1227** [comment]
> Is there any problem in this plugin with the latest version of Acode? If yes , then definitely I will provide update. Please check and tell me

The command palette in this most recent version of acode, seems to be obsolete, and there is no way to access the plugin without it, you could put a bindKey to activate it.

**Comment by CaRLos1227** [comment]
> Is there any problem in this plugin with the latest version of Acode? If yes , then definitely I will provide update. Please check and tell me

The command palette in this most recent version of acode, seems to be obsolete, and there is no way to access the plugin without it, you could put a bindKey to activate it.

**Comment by bajrangCoder** [comment]
Ok
Btw still you can open Command palette either via <kbd>Ctrl+Shift+P</kbd> or <kbd>F1</kbd>

**Comment by CaRLos1227** [comment]
> Ok Btw still you can open Command palette either via Ctrl+Shift+P or F1

Lol thanks I didn't really know about that shortcut thanks.
